### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by ednawig** [bobvandevijver/latex-bundle#10]
Captions in tables seem not to work - pdflatex throws this "LaTeX Error: \caption outside float".

One way to fix this is to wrap the tabular(x) environment inside a table environment with the caption outside the tabularx. Something like this:

\begin{table}
      \resizebox{\textwidth}{!}{
      \begin{tabularx}{\textwidth}{lll }
.....

    \end{tabularx}
      }
              \caption{Table caption}
\end{table}

But I think that one cannot use toprule etc. with this.

**Comment by bobvandevijver** [comment]
Can you post the complete tabularx source which generates the error? Than I can easily debug using a local latex editor and decide which solution works better. 

At the moment I am thinking of the table environment, but only when a caption is required. This as the table environment also adds extra spacing, and I need to check what resizebox does...

**Comment by ednawig** [comment]
Here it is:

  \clearpage
  \maketitle
  \thispagestyle{empty}
  \newpage
        % Table element
    
      \resizebox{\textwidth}{!}{
      \begin{tabularx}{\textwidth}{lll }
              \caption{Table Caption}
                              a & b & c \\
                                d & e & f \\
                                g & h & i \\
              
    \end{tabularx}

      }
    
  \end{document}

**Comment by bobvandevijver** [comment]
I've fixed it now; i've only added the table environment when you use the caption. This way, spacing does not change for people who use this element without using the caption (like me :)). People who do use the caption can fix the spacing themselves using the adequate commands.
