### ISSUE TITLE
pdflatex not found

### ISSUE THREAD

**Issue by CKESSLER** [bobvandevijver/latex-bundle#26]
Thanks for this usefull tool.
However i have a problem, It's seems that php cannot found pdflatex.
I have to change **pdflatex** to **/usr/bin/pdflatex** in LatexGenerator class to generate successfully  pdf file.

`$process = new Process("cd " . $this->outputDir . " && HOME=\"/tmp\" pdflatex " . $optionsString . " -interaction=nonstopmode -output-directory=\"" . $this->outputDir . "\" \"$texLocation\"");`
to
`$process = new Process("cd " . $this->outputDir . " && HOME=\"/tmp\" /usr/bin/pdflatex " . $optionsString . " -interaction=nonstopmode -output-directory=\"" . $this->outputDir . "\" \"$texLocation\"");`
(LatexGenerator l.324)

Do you have an idea to fix this?

**Comment by bobvandevijver** [comment]
This seems to be related to the `PATH` environment that is available when you're executing the command. You should be able to configure your web user to have the `/usr/bin` path available. 
In my environment the pdflatex location is the same, but it most certainly does work without the full path.

You can check your path with `$_ENV` or `getenv()` (although they [seem to be different](http://php.net/manual/en/reserved.variables.environment.php)). 
To solve the problem, try to put the following in you calling code: `setevn('PATH=/usr/bin')`.

It would actually make sense to have the pdflatex command location configurable in the bundle settings, so I might be looking into that later today.

**Comment by bobvandevijver** [comment]
I've created a new branch (`pdflatex-location`), can you try it and report back the results? You can simply set the `%bobv.latex.pdflatex.location%` parameter to `/usr/bin/pdflatex`.

**Comment by CKESSLER** [comment]
Thanks you for your response.
I will try this tomorrow and report back as soon as possible.

Le 16 nov. 2017 9:37 PM, "Bob van de Vijver" <notifications@github.com> a
écrit :

I've created a new branch (pdflatex-location), can you try it and report
back the results? You can simply set the %bobv.latex.pdflatex.location%
parameter to /usr/bin/pdflatex.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bobvandevijver/latex-bundle/issues/26#issuecomment-345054825>,
or mute the thread

**Comment by CKESSLER** [comment]
Hello,

I've tried it and it's work for me.
I just think you forget a % in service.yml ("%bobv.latex.pdflatex.location")

Thanks *for **your time*.

[image: photo]
*Cyril KESSLER*
Directeur des systèmes d'informations, Groupe Réussite
0682614541 | c.kessler@groupe-reussite.fr | https://groupe-reussite.fr/ | 12
rue Duguay Trouin 75006 Paris
Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

2017-11-16 21:45 GMT+01:00 Cyril Kessler <cyril.kessler@gmail.com>:

**Comment by bobvandevijver** [comment]
I see, I've updated it and will merge it to master. Thanks for testing!

**Comment by bobvandevijver** [comment]
Fixed with #27.
