### ISSUE TITLE
Numbering toc

### ISSUE THREAD

**Issue by orioll197** [bobvandevijver/latex-bundle#31]
Hello, yesterday I began to use this plugin in symfony but I can't find a way to number the toc, do you have any Idea on how to do it?

**Comment by bobvandevijver** [comment]
You probably want to set the `secnumdepth` of the base LaTeX element you're using (for example [Article](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/doc/base/Article.md)) to anything other than 0, which is the default. 

Next to the `secnumdepth` parameter of the base element, the configuration of the TOC can be completely customised as you would do with any normal LaTeX document. You can insert any LaTeX command in preamble by using the `extraCommands` functionality (for example, by using the [`CustomCommand` element](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/doc/element/custom_command.md). 

The [TOC element](https://github.com/bobvandevijver/latex-bundle/blob/master/Latex/Element/TOC.php) self does not take any parameters, and it does not do much more than inserting the TOC command combined with a newpage (see [template](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/views/Element/toc.tex.twig)). But, as always, you can insert a custom command in front.

**Comment by orioll197** [comment]
Okay, solved, thank you! ^^
By the way is there any way for not downloading the pdf ans saving it on any other location on the server?

**Comment by bobvandevijver** [comment]
Yes there is, see the [docs](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/doc/documentation.md):

```php
// Compile a PDF from a LaTeX object
$pdfLocation = $latexGenerator->generate($latex);
```
