### ISSUE TITLE
With Laravel 6.3 getting a Container EntryNotFoundException

### ISSUE THREAD

**Issue by datapoesy** [bobvandevijver/latex-bundle#37]
Hi,
I am getting a Illuminate\Container\EntryNotFoundException
bobv.latex.generator with Laravel 6.3.

Is there any solution for the above; not sure whether I am missing something here.

thanks,

**Comment by bobvandevijver** [comment]
I do not have any experience with Laravel itself, but from what I can quickly find I it is not directly possible to use a Symfony bundle with it. The container and the dependency injection configuration looks quite different from Symfony as well. 

You might still be able to use this bundle, but you'll probably need to configure the container yourself. However, I do not think that should be really hard, you just need to translate the [services.yml](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/config/services.yml) to the appropriate format that Laravel can understand. Luckily (at this moment), this bundle does not use any CompilerPass or configuration that needs to be translated as well.

I will close this issue though as this bundle does not support Laravel (and I also have no plans to do so).

**Comment by datapoesy** [comment]
hi Bob,

Appreciate your response.  I will explore if there are any workarounds to use this package with Laravel.  Thanks again,
