### ISSUE TITLE
How do I configure as to use either one of different installs of texlive

### ISSUE THREAD

**Issue by mario6097** [bobvandevijver/latex-bundle#38]
Hi
I have two different installs  of Texlive on my machine. How/where do I configure latex-bundle as to use either one? 
Thanks Regards
mario

**Comment by bobvandevijver** [comment]
You can find the answer in the [documentation](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/doc/documentation.md#pdflatex-location). Basically, you can specify the absolute path of the installation you want to use by overwriting the `bobv.latex.pdflatex.location` variable.

**Comment by mario6097** [comment]
yes, i misses that, thanks. Very useful package.
