### ISSUE TITLE
is biber there too? 

### ISSUE THREAD

**Issue by mario6097** [bobvandevijver/latex-bundle#39]
Hi

is biber implemented?
thanks regards
mario

**Comment by mario6097** [comment]
as a temporary fix, I inserted the following lines of code within LatexGenerator.php, at line 378. It works, at least for my present project (otherwise `\printbibliography` is not rendered). I am an  amateurish user of Symfony, so I am not sure how you should really go to fix it. 

```
      /// NEW
      if($count==1){
      $bibLocation = explode('.tex', $texLocation)[0];
      $commandLine =   'biber  '.$bibLocation;
      if (method_exists(Process::class, 'fromShellCommandline')) {
        $process = Process::fromShellCommandline($commandLine);
      } else {
        $process = new Process($commandLine);
      }
     $process->run();
 }  //// END NEW
```

**Comment by bobvandevijver** [comment]
This bundle currently only supports running the `pdflatex` and doesn't do anything with with bibliography. But, that doesn't mean we can't start supporting it.

Your code looks valid, but before we can merge it in the bundle we'll need to change a few things:
- The behavior needs to disabled by default to be backwards compatible, so we need a parameter for it (can possibly combined with the next on)
- We need to be able to configure the used tool as there are alternatives for biber (such as bibtex)
- I guess I would place it just before the `$count++` on line 378 for only the `$count === 0`. 
- It needs to have a dedicated exception for when the command fails

Would you like to take a go at creating a merge request?

I still need to find some time to convert the [current parameters and service definition](https://github.com/bobvandevijver/latex-bundle/blob/master/Resources/config/services.yml) into the nowadays recommended bundle configuration structure, but for this MR you can use the old style I guess.

**Comment by mario6097** [comment]
Hi,
thanks for your reply. I have just a very basic understanding about merge (pull?) request. Happy to help, but I am not confident I may do too much.
