### ISSUE TITLE
Fix object for callback latexParseHtml

### ISSUE THREAD

**Issue by BenjaminLeseur** [bobvandevijver/latex-bundle#46]
Hello,
The function `latexParseHtml` exists in `$this` object (`\BobV\LatexBundle\Twig\BobVLatexExtension`), not in `$this->parser`, as seen here:

https://github.com/bobvandevijver/latex-bundle/blob/09505520920ab2d63fa34960ca98a55466c63b74/src/Twig/BobVLatexExtension.php#L37

Can you check if I am right and fix the callback definition?

**Comment by bobvandevijver** [comment]
Should be fixed with [v2.7.3](https://github.com/bobvandevijver/latex-bundle/releases/tag/v2.7.3)!

**Comment by BenjaminLeseur** [comment]
Thank you!
