### ISSUE TITLE
I am not able to install latest version on Synfony 6.1.3

### ISSUE THREAD

**Issue by mario6097** [bobvandevijver/latex-bundle#47]
HI
I am not sure if this a real issue, or what.
I am trying to install the latest  v2.8.0 latex-bundle on an install of Symfony 6.1.3. Is it possible?
I tried the following.

$ **/usr/bin/composer require   bobv/latex-bundle:2.8.0**
./composer.json has been updated
Running composer update bobv/latex-bundle
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bobv/latex-bundle 2.8.0 -> satisfiable by bobv/latex-bundle[v2.8.0].
    - bobv/latex-bundle v2.8.0 requires symfony/config ~3.4 || ~4.3 || ~5.0 -> found symfony/config[v3.4.0, ..., v3.4.47, v4.3.0, ..., v4.4.44, v5.0.0, ..., v5.4.11] but it conflicts with your root composer.json require (6.1.*).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

 $ **/usr/bin/composer require --with-all-dependencies   bobv/latex-bundle:2.8.0**
./composer.json has been updated
Running composer update bobv/latex-bundle --with-all-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.1.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bobv/latex-bundle 2.8.0 -> satisfiable by bobv/latex-bundle[v2.8.0].
    - bobv/latex-bundle v2.8.0 requires symfony/config ~3.4 || ~4.3 || ~5.0 -> found symfony/config[v3.4.0, ..., v3.4.47, v4.3.0, ..., v4.4.44, v5.0.0, ..., v5.4.11] but it conflicts with your root composer.json require (6.1.*).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

 $   **/usr/bin/composer require --with-all-dependencies   bobv/latex-bundle:***
./composer.json has been updated
Running composer update bobv/latex-bundle --with-all-dependencies
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.1.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - __root__ 1.0.0+no-version-set conflicts with symfony/symfony v6.1.4.
    - __root__ 1.0.0+no-version-set conflicts with symfony/symfony v6.1.3.
    - __root__ 1.0.0+no-version-set conflicts with symfony/symfony v6.1.2.
    - __root__ 1.0.0+no-version-set conflicts with symfony/symfony v6.1.1.
    - __root__ 1.0.0+no-version-set conflicts with symfony/symfony v6.1.0.
    - __root__ is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - Root composer.json requires symfony/dotenv 6.1.* -> satisfiable by symfony/symfony[v6.1.0, ..., v6.1.4].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

 $  **/usr/bin/composer require  bobv/latex-bundle:***
./composer.json has been updated
Running composer update bobv/latex-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "6.1.*"
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
61 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
No security vulnerability advisories found

---------------

Am i missing something? 
Thanks Cheers

**Comment by bobvandevijver** [comment]
Hmm, I did not update this bundle for Symfony 6 yet because I have no Symfony 6 projects yet (I mostly stay on LTS), so that would the cause.

Can you try the Symfony 6 branch with `composer req bobv/latex-bundle:dev-sf6`? There might be some issues with the return types, please let me know when they occur/add the fixed to #48?

**Comment by mario6097** [comment]
Bob, thanks so much, I tried `dev-sf6` and it seems to work fine. I let you know of any issue.
